/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/api/config': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** 获取配置信息 */
    get: operations['config.index'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/md/content': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** 读取 markdown 文件原文 */
    get: operations['md.content'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/md/list': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** 列出目录下的 markdown 文件 */
    get: operations['md.list'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/opener/delete': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** 按名删除 opener */
    post: operations['opener.delete'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/opener/extract-icon': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** 从本地 .app 提取图标（64px PNG，base64） */
    post: operations['opener.extractIcon'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/opener/info': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** 获取 opener 详情 */
    get: operations['opener.info'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/opener/list': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** 获取 opener 列表 */
    get: operations['opener.list'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/opener/open': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** 用指定 opener 打开任意文件或目录 */
    post: operations['opener.open'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/opener/save': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** 新增或更新 opener（按 name 替换） */
    post: operations['opener.save'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/project/clone-rules': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** 获取 clone 规则 */
    get: operations['project.cloneRules'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/project/info': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** 获取项目详情 */
    get: operations['project.info'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/project/list': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** 获取项目列表 */
    get: operations['project.list'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/project/scan-rules': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** 获取扫描规则 */
    get: operations['project.scanRules'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/system/whoami': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** 服务身份探活 */
    get: operations['system.whoami'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/workbench/changes': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** 列出源相对上一版本的变更文件 */
    get: operations['workbench.changes'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/workbench/commits': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** 拉取工作台 commit 图（分页） */
    get: operations['workbench.commits'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/workbench/diff': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** 双 TreeSource 目录级对比 */
    get: operations['workbench.diff'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/workbench/file': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** 读取 TreeSource 下的文件内容 */
    get: operations['workbench.file'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/workbench/file-diff': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** 双 TreeSource 单文件 diff */
    get: operations['workbench.fileDiff'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/workbench/file/save': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** 保存工作副本文件（唯一写路径） */
    post: operations['workbench.fileSave'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/workbench/info': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** 获取工作台项目信息 */
    get: operations['workbench.info'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/workbench/refs': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** 获取工作台分支与tag列表 */
    get: operations['workbench.refs'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/workbench/remotes': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** 获取工作台 remote 列表 */
    get: operations['workbench.remotes'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/workbench/tree': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** 列出 TreeSource 下的目录树 */
    get: operations['workbench.tree'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/workbench/worktrees': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** 全部工作副本的状态快照 */
    get: operations['workbench.worktrees'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    ApiOutputCommitsPageResultBody: {
      /**
       * Format: uri
       * @description A URL to the JSON Schema for this object.
       * @example https://example.com/schemas/ApiOutputCommitsPageResultBody.json
       */
      readonly $schema?: string;
      data: components['schemas']['CommitsPageResult'];
      message: string;
      ok: boolean;
    };
    ApiOutputConfigBody: {
      /**
       * Format: uri
       * @description A URL to the JSON Schema for this object.
       * @example https://example.com/schemas/ApiOutputConfigBody.json
       */
      readonly $schema?: string;
      data: components['schemas']['Config'];
      message: string;
      ok: boolean;
    };
    ApiOutputDiffTreesResultBody: {
      /**
       * Format: uri
       * @description A URL to the JSON Schema for this object.
       * @example https://example.com/schemas/ApiOutputDiffTreesResultBody.json
       */
      readonly $schema?: string;
      data: components['schemas']['DiffTreesResult'];
      message: string;
      ok: boolean;
    };
    ApiOutputFileDiffResultBody: {
      /**
       * Format: uri
       * @description A URL to the JSON Schema for this object.
       * @example https://example.com/schemas/ApiOutputFileDiffResultBody.json
       */
      readonly $schema?: string;
      data: components['schemas']['FileDiffResult'];
      message: string;
      ok: boolean;
    };
    ApiOutputFileResultBody: {
      /**
       * Format: uri
       * @description A URL to the JSON Schema for this object.
       * @example https://example.com/schemas/ApiOutputFileResultBody.json
       */
      readonly $schema?: string;
      data: components['schemas']['FileResult'];
      message: string;
      ok: boolean;
    };
    ApiOutputInfoBody: {
      /**
       * Format: uri
       * @description A URL to the JSON Schema for this object.
       * @example https://example.com/schemas/ApiOutputInfoBody.json
       */
      readonly $schema?: string;
      data: components['schemas']['Info'];
      message: string;
      ok: boolean;
    };
    ApiOutputListRemoteEntryBody: {
      /**
       * Format: uri
       * @description A URL to the JSON Schema for this object.
       * @example https://example.com/schemas/ApiOutputListRemoteEntryBody.json
       */
      readonly $schema?: string;
      data: components['schemas']['RemoteEntry'][] | null;
      message: string;
      ok: boolean;
    };
    ApiOutputListResultCloneRuleBody: {
      /**
       * Format: uri
       * @description A URL to the JSON Schema for this object.
       * @example https://example.com/schemas/ApiOutputListResultCloneRuleBody.json
       */
      readonly $schema?: string;
      data: components['schemas']['ListResultCloneRule'];
      message: string;
      ok: boolean;
    };
    ApiOutputListResultOpenerDTOBody: {
      /**
       * Format: uri
       * @description A URL to the JSON Schema for this object.
       * @example https://example.com/schemas/ApiOutputListResultOpenerDTOBody.json
       */
      readonly $schema?: string;
      data: components['schemas']['ListResultOpenerDTO'];
      message: string;
      ok: boolean;
    };
    ApiOutputListResultScanRuleBody: {
      /**
       * Format: uri
       * @description A URL to the JSON Schema for this object.
       * @example https://example.com/schemas/ApiOutputListResultScanRuleBody.json
       */
      readonly $schema?: string;
      data: components['schemas']['ListResultScanRule'];
      message: string;
      ok: boolean;
    };
    ApiOutputListWorktreeStatusBody: {
      /**
       * Format: uri
       * @description A URL to the JSON Schema for this object.
       * @example https://example.com/schemas/ApiOutputListWorktreeStatusBody.json
       */
      readonly $schema?: string;
      data: components['schemas']['WorktreeStatus'][] | null;
      message: string;
      ok: boolean;
    };
    'ApiOutputMapStringInterface {}Body': {
      /**
       * Format: uri
       * @description A URL to the JSON Schema for this object.
       * @example https://example.com/schemas/ApiOutputMapStringInterface {}Body.json
       */
      readonly $schema?: string;
      data: {
        [key: string]: unknown;
      };
      message: string;
      ok: boolean;
    };
    ApiOutputMdContentResultBody: {
      /**
       * Format: uri
       * @description A URL to the JSON Schema for this object.
       * @example https://example.com/schemas/ApiOutputMdContentResultBody.json
       */
      readonly $schema?: string;
      data: components['schemas']['MdContentResult'];
      message: string;
      ok: boolean;
    };
    ApiOutputMdListResultBody: {
      /**
       * Format: uri
       * @description A URL to the JSON Schema for this object.
       * @example https://example.com/schemas/ApiOutputMdListResultBody.json
       */
      readonly $schema?: string;
      data: components['schemas']['MdListResult'];
      message: string;
      ok: boolean;
    };
    ApiOutputOpenerDTOBody: {
      /**
       * Format: uri
       * @description A URL to the JSON Schema for this object.
       * @example https://example.com/schemas/ApiOutputOpenerDTOBody.json
       */
      readonly $schema?: string;
      data: components['schemas']['OpenerDTO'];
      message: string;
      ok: boolean;
    };
    ApiOutputProjectInfoResultBody: {
      /**
       * Format: uri
       * @description A URL to the JSON Schema for this object.
       * @example https://example.com/schemas/ApiOutputProjectInfoResultBody.json
       */
      readonly $schema?: string;
      data: components['schemas']['ProjectInfoResult'];
      message: string;
      ok: boolean;
    };
    ApiOutputProjectListResultBody: {
      /**
       * Format: uri
       * @description A URL to the JSON Schema for this object.
       * @example https://example.com/schemas/ApiOutputProjectListResultBody.json
       */
      readonly $schema?: string;
      data: components['schemas']['ProjectListResult'];
      message: string;
      ok: boolean;
    };
    ApiOutputRefsBody: {
      /**
       * Format: uri
       * @description A URL to the JSON Schema for this object.
       * @example https://example.com/schemas/ApiOutputRefsBody.json
       */
      readonly $schema?: string;
      data: components['schemas']['Refs'];
      message: string;
      ok: boolean;
    };
    ApiOutputTreeListResultBody: {
      /**
       * Format: uri
       * @description A URL to the JSON Schema for this object.
       * @example https://example.com/schemas/ApiOutputTreeListResultBody.json
       */
      readonly $schema?: string;
      data: components['schemas']['TreeListResult'];
      message: string;
      ok: boolean;
    };
    ApiOutputWhoamiResponseBody: {
      /**
       * Format: uri
       * @description A URL to the JSON Schema for this object.
       * @example https://example.com/schemas/ApiOutputWhoamiResponseBody.json
       */
      readonly $schema?: string;
      data: components['schemas']['WhoamiResponse'];
      message: string;
      ok: boolean;
    };
    CloneRule: {
      localPath: string;
      repoHost: string;
      repoPrefix: string;
    };
    CloneRuleConfig: {
      localPath: string;
      repoHost: string;
      repoPrefix: string;
    };
    CommitEntry: {
      author: string;
      parents: string[] | null;
      refs: components['schemas']['CommitRef'][] | null;
      sha: string;
      shortSha: string;
      subject: string;
      /** Format: int64 */
      timestamp: number;
    };
    CommitRef: {
      kind: string;
      name: string;
    };
    CommitsPageResult: {
      hasMore: boolean;
      list: components['schemas']['CommitEntry'][] | null;
      /** Format: int64 */
      nextCursor: number;
    };
    Config: {
      create: components['schemas']['CreateConfig'];
      dataDir: string;
      log: components['schemas']['LogConfig'];
      project: components['schemas']['ProjectConfig'];
      server: components['schemas']['ServerConfig'];
    };
    CreateConfig: {
      templateSource: string;
    };
    DiffEntry: {
      /** Format: int64 */
      adds: number;
      binary: boolean;
      /** Format: int64 */
      dels: number;
      oldPath: string;
      path: string;
      status: string;
    };
    DiffLine: {
      kind: string;
      text: string;
    };
    DiffTreesResult: {
      list: components['schemas']['DiffEntry'][] | null;
      mode: string;
    };
    Entry: {
      /** Format: int64 */
      ahead: number;
      /** Format: int64 */
      behind: number;
      branches: string[] | null;
      /** Format: date-time */
      collectedAt: string;
      currentBranch: string;
      defaultBranch: string;
      dirty: boolean;
      repoUrl: string;
      worktreeMain: string;
    };
    ErrorDetail: {
      /** @description Where the error occurred, e.g. 'body.items[3].tags' or 'path.thing-id' */
      location?: string;
      /** @description Error message text */
      message?: string;
      /** @description The value at the given location */
      value?: unknown;
    };
    ErrorModel: {
      /**
       * Format: uri
       * @description A URL to the JSON Schema for this object.
       * @example https://example.com/schemas/ErrorModel.json
       */
      readonly $schema?: string;
      /**
       * @description A human-readable explanation specific to this occurrence of the problem.
       * @example Property foo is required but is missing.
       */
      detail?: string;
      /** @description Optional list of individual error details */
      errors?: components['schemas']['ErrorDetail'][] | null;
      /**
       * Format: uri
       * @description A URI reference that identifies the specific occurrence of the problem.
       * @example https://example.com/error-log/abc123
       */
      instance?: string;
      /**
       * Format: int64
       * @description HTTP status code
       * @example 400
       */
      status?: number;
      /**
       * @description A short, human-readable summary of the problem type. This value should not change between occurrences of the error.
       * @example Bad Request
       */
      title?: string;
      /**
       * Format: uri
       * @description A URI reference to human-readable documentation for the error.
       * @default about:blank
       * @example https://example.com/errors/example
       */
      type: string;
    };
    FileDiffResult: {
      binary: boolean;
      hunks: components['schemas']['Hunk'][] | null;
    };
    FileResult: {
      binary: boolean;
      content: string;
      deleted: boolean;
      /** Format: int64 */
      size: number;
    };
    FileSaveRequest: {
      /**
       * Format: uri
       * @description A URL to the JSON Schema for this object.
       * @example https://example.com/schemas/FileSaveRequest.json
       */
      readonly $schema?: string;
      content: string;
      file: string;
      path: string;
      source: string;
    };
    Hunk: {
      lines: components['schemas']['DiffLine'][] | null;
      /** Format: int64 */
      newCount: number;
      /** Format: int64 */
      newStart: number;
      /** Format: int64 */
      oldCount: number;
      /** Format: int64 */
      oldStart: number;
    };
    Info: {
      defaultBranch: string;
      root: string;
    };
    ListResultCloneRule: {
      list: components['schemas']['CloneRule'][] | null;
    };
    ListResultOpenerDTO: {
      list: components['schemas']['OpenerDTO'][] | null;
    };
    ListResultScanRule: {
      list: components['schemas']['ScanRule'][] | null;
    };
    LogConfig: {
      format: string;
      level: string;
      path: string;
    };
    MdContentResult: {
      content: string;
    };
    MdListResult: {
      dir: boolean;
      files: string[] | null;
    };
    OpenerDTO: {
      icon: components['schemas']['OpenerIconDTO'];
      name: string;
      roles: string[] | null;
      summary: string;
      title: string;
    };
    OpenerDeleteInputBody: {
      /**
       * Format: uri
       * @description A URL to the JSON Schema for this object.
       * @example https://example.com/schemas/OpenerDeleteInputBody.json
       */
      readonly $schema?: string;
      /** @description opener 名称 */
      name: string;
    };
    OpenerExtractIconInputBody: {
      /**
       * Format: uri
       * @description A URL to the JSON Schema for this object.
       * @example https://example.com/schemas/OpenerExtractIconInputBody.json
       */
      readonly $schema?: string;
      /** @description .app 目录绝对路径 */
      path: string;
    };
    OpenerIconDTO: {
      type: string;
      value: string;
    };
    OpenerOpenInputBody: {
      /**
       * Format: uri
       * @description A URL to the JSON Schema for this object.
       * @example https://example.com/schemas/OpenerOpenInputBody.json
       */
      readonly $schema?: string;
      /** @description opener 名称 */
      opener: string;
      /** @description 文件或目录绝对路径 */
      path: string;
    };
    OpenerSaveInputBody: {
      /**
       * Format: uri
       * @description A URL to the JSON Schema for this object.
       * @example https://example.com/schemas/OpenerSaveInputBody.json
       */
      readonly $schema?: string;
      /** @description 启动命令，$0/$1 占位路径槽位 */
      cmd?: string[] | null;
      /** @description 图标声明 */
      icon?: components['schemas']['OpenerIconDTO'];
      /** @description opener 名称（唯一标识） */
      name: string;
      /** @description 业务用途枚举，缺省视为 open-dir */
      roles?: string[] | null;
      /** @description 展示文案（如「打开所在目录」），缺省由 name 生成 */
      title?: string;
    };
    ProjectConfig: {
      clone: components['schemas']['CloneRuleConfig'][] | null;
      scan: components['schemas']['ScanRuleConfig'][] | null;
    };
    ProjectDTO: {
      gitInfo: components['schemas']['Entry'];
      group: string;
      name: string;
      path: string;
      tags: string[] | null;
    };
    ProjectInfoResult: {
      /** Format: date-time */
      gitUpdatedAt: string;
      project: components['schemas']['ProjectDTO'];
      /** Format: date-time */
      scanUpdatedAt: string;
    };
    ProjectListResult: {
      /** Format: date-time */
      gitUpdatedAt: string;
      list: components['schemas']['ProjectDTO'][] | null;
      /** Format: date-time */
      scanUpdatedAt: string;
    };
    Refs: {
      head: string;
      locals: string[] | null;
      remotes: string[] | null;
      tags: string[] | null;
    };
    RemoteEntry: {
      name: string;
      url: string;
      webUrl: string;
    };
    ScanRule: {
      group: string;
      /** Format: int64 */
      maxDepth: number;
      path: string;
    };
    ScanRuleConfig: {
      group: string;
      /** Format: int64 */
      maxDepth: number;
      path: string;
    };
    ServerConfig: {
      /** Format: int64 */
      port: number;
    };
    TreeListResult: {
      list: string[] | null;
    };
    WhoamiResponse: {
      app: string;
      version: string;
    };
    WorktreeStatus: {
      /** Format: int64 */
      ahead: number;
      bare: boolean;
      /** Format: int64 */
      behind: number;
      branch: string;
      detached: boolean;
      dirty: boolean;
      head: string;
      path: string;
      /** Format: int64 */
      staged: number;
      /** Format: int64 */
      unstaged: number;
      /** Format: int64 */
      untracked: number;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  'config.index': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ApiOutputConfigBody'];
        };
      };
      /** @description Error */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['ErrorModel'];
        };
      };
    };
  };
  'md.content': {
    parameters: {
      query: {
        path: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ApiOutputMdContentResultBody'];
        };
      };
      /** @description Error */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['ErrorModel'];
        };
      };
    };
  };
  'md.list': {
    parameters: {
      query: {
        path: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ApiOutputMdListResultBody'];
        };
      };
      /** @description Error */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['ErrorModel'];
        };
      };
    };
  };
  'opener.delete': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['OpenerDeleteInputBody'];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ApiOutputMapStringInterface {}Body'];
        };
      };
      /** @description Error */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['ErrorModel'];
        };
      };
    };
  };
  'opener.extractIcon': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['OpenerExtractIconInputBody'];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ApiOutputMapStringInterface {}Body'];
        };
      };
      /** @description Error */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['ErrorModel'];
        };
      };
    };
  };
  'opener.info': {
    parameters: {
      query: {
        name: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ApiOutputOpenerDTOBody'];
        };
      };
      /** @description Error */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['ErrorModel'];
        };
      };
    };
  };
  'opener.list': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ApiOutputListResultOpenerDTOBody'];
        };
      };
      /** @description Error */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['ErrorModel'];
        };
      };
    };
  };
  'opener.open': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['OpenerOpenInputBody'];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ApiOutputMapStringInterface {}Body'];
        };
      };
      /** @description Error */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['ErrorModel'];
        };
      };
    };
  };
  'opener.save': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['OpenerSaveInputBody'];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ApiOutputMapStringInterface {}Body'];
        };
      };
      /** @description Error */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['ErrorModel'];
        };
      };
    };
  };
  'project.cloneRules': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ApiOutputListResultCloneRuleBody'];
        };
      };
      /** @description Error */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['ErrorModel'];
        };
      };
    };
  };
  'project.info': {
    parameters: {
      query: {
        name: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ApiOutputProjectInfoResultBody'];
        };
      };
      /** @description Error */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['ErrorModel'];
        };
      };
    };
  };
  'project.list': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ApiOutputProjectListResultBody'];
        };
      };
      /** @description Error */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['ErrorModel'];
        };
      };
    };
  };
  'project.scanRules': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ApiOutputListResultScanRuleBody'];
        };
      };
      /** @description Error */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['ErrorModel'];
        };
      };
    };
  };
  'system.whoami': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ApiOutputWhoamiResponseBody'];
        };
      };
      /** @description Error */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['ErrorModel'];
        };
      };
    };
  };
  'workbench.changes': {
    parameters: {
      query: {
        path: string;
        source: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ApiOutputDiffTreesResultBody'];
        };
      };
      /** @description Error */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['ErrorModel'];
        };
      };
    };
  };
  'workbench.commits': {
    parameters: {
      query: {
        path: string;
        cursor?: number;
        limit?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ApiOutputCommitsPageResultBody'];
        };
      };
      /** @description Error */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['ErrorModel'];
        };
      };
    };
  };
  'workbench.diff': {
    parameters: {
      query: {
        path: string;
        base: string;
        current: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ApiOutputDiffTreesResultBody'];
        };
      };
      /** @description Error */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['ErrorModel'];
        };
      };
    };
  };
  'workbench.file': {
    parameters: {
      query: {
        path: string;
        source: string;
        file: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ApiOutputFileResultBody'];
        };
      };
      /** @description Error */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['ErrorModel'];
        };
      };
    };
  };
  'workbench.fileDiff': {
    parameters: {
      query: {
        path: string;
        base?: string;
        current: string;
        file: string;
        baseFile?: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ApiOutputFileDiffResultBody'];
        };
      };
      /** @description Error */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['ErrorModel'];
        };
      };
    };
  };
  'workbench.fileSave': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['FileSaveRequest'];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ApiOutputFileResultBody'];
        };
      };
      /** @description Error */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['ErrorModel'];
        };
      };
    };
  };
  'workbench.info': {
    parameters: {
      query: {
        path: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ApiOutputInfoBody'];
        };
      };
      /** @description Error */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['ErrorModel'];
        };
      };
    };
  };
  'workbench.refs': {
    parameters: {
      query: {
        path: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ApiOutputRefsBody'];
        };
      };
      /** @description Error */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['ErrorModel'];
        };
      };
    };
  };
  'workbench.remotes': {
    parameters: {
      query: {
        path: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ApiOutputListRemoteEntryBody'];
        };
      };
      /** @description Error */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['ErrorModel'];
        };
      };
    };
  };
  'workbench.tree': {
    parameters: {
      query: {
        path: string;
        source: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ApiOutputTreeListResultBody'];
        };
      };
      /** @description Error */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['ErrorModel'];
        };
      };
    };
  };
  'workbench.worktrees': {
    parameters: {
      query: {
        path: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ApiOutputListWorktreeStatusBody'];
        };
      };
      /** @description Error */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['ErrorModel'];
        };
      };
    };
  };
}
