// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

import (
	"github.com/heyuuu/go-cube/internal/services"
)

// Injectors from wire.go:

func InitApp() *App {
	projectService := services.NewProjectService()
	applicationService := services.NewApplicationService()
	repoService := services.NewRepoService()
	app := &App{
		projectService:     projectService,
		applicationService: applicationService,
		repoService:        repoService,
	}
	return app
}
