// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

import (
	"github.com/heyuuu/go-cube/internal/config"
	"github.com/heyuuu/go-cube/internal/handlers"
	"github.com/heyuuu/go-cube/internal/server"
	"github.com/heyuuu/go-cube/internal/services"
)

// Injectors from wire.go:

func InitApp() *App {
	configConfig := config.Default()
	configService := services.NewConfigService(configConfig)
	configHandler := handlers.NewConfigHandler(configService)
	workspaceService := services.NewWorkspaceService(configConfig)
	projectService := services.NewProjectService(workspaceService)
	projectHandler := handlers.NewProjectHandler(projectService)
	workspaceHandler := handlers.NewWorkspaceHandler(workspaceService)
	v := handlers.AllHandlers(configHandler, projectHandler, workspaceHandler)
	serverServer := server.NewServer(v)
	applicationService := services.NewApplicationService(configConfig)
	remoteService := services.NewRemoteService(configConfig)
	app := &App{
		server:             serverServer,
		workspaceService:   workspaceService,
		projectService:     projectService,
		applicationService: applicationService,
		remoteService:      remoteService,
	}
	return app
}
